#ifndef SKATER_SPRITES_DEFINITION 
#define SKATER_SPRITES_DEFINITION

char skater_sprite_data [] = {
    0xFF, 0xFF, 0XFF, 0XFF, 0XFF, 0XFF, 0XFF, 0XFF, 0XFF,
    0xFF, 0xFF, 0XFF, 0XFF, 0XFF, 0XFF, 0XFF, 0XFF, 0XFF 
};

#endif